"""empty message

Revision ID: b0568bfcc3f5
Revises: f6fadc81c17d
Create Date: 2019-05-30 10:19:44.809179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0568bfcc3f5'
down_revision = 'f6fadc81c17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_phone_no', table_name='contact')
    op.create_index(op.f('ix_contact_phone_no'), 'contact', ['phone_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_phone_no'), table_name='contact')
    op.create_index('ix_contact_phone_no', 'contact', ['phone_no'], unique=1)
    # ### end Alembic commands ###
