"""empty message

Revision ID: f6fadc81c17d
Revises: 
Create Date: 2019-05-30 08:54:10.189711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fadc81c17d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_name', sa.String(length=200), nullable=True),
    sa.Column('code_name', sa.String(length=200), nullable=True),
    sa.Column('phone_no', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_actual_name'), 'contact', ['actual_name'], unique=False)
    op.create_index(op.f('ix_contact_code_name'), 'contact', ['code_name'], unique=True)
    op.create_index(op.f('ix_contact_phone_no'), 'contact', ['phone_no'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_contact_phone_no'), table_name='contact')
    op.drop_index(op.f('ix_contact_code_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_actual_name'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
